title: Briding the Gap Survey
description: A website for the 'Bridging the Gap A Survey on Integrating (Human) Feedback for Natural Language Generation' survey
google_analytics:
theme: jekyll-theme-cayman